// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDlo7PAka2mZYNNd6K-Hy0oftsqKJHYME',
    appId: '1:645777275077:web:b2e50e0a0ea41b203ed8ac',
    messagingSenderId: '645777275077',
    projectId: 'fir-group-855b2',
    authDomain: 'fir-group-855b2.firebaseapp.com',
    storageBucket: 'fir-group-855b2.appspot.com',
    measurementId: 'G-2NCBB2GSW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX49irDqVp59aInKl8yDZvxxE5jGh-9NE',
    appId: '1:645777275077:android:721a2a8925b04f413ed8ac',
    messagingSenderId: '645777275077',
    projectId: 'fir-group-855b2',
    storageBucket: 'fir-group-855b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABNEM2-bA6ILiSE9Loo2ooy-7R6oNT044',
    appId: '1:645777275077:ios:6ab5e662e271e5a53ed8ac',
    messagingSenderId: '645777275077',
    projectId: 'fir-group-855b2',
    storageBucket: 'fir-group-855b2.appspot.com',
    iosBundleId: 'com.example.sGroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABNEM2-bA6ILiSE9Loo2ooy-7R6oNT044',
    appId: '1:645777275077:ios:61ea1a62d5f7bc733ed8ac',
    messagingSenderId: '645777275077',
    projectId: 'fir-group-855b2',
    storageBucket: 'fir-group-855b2.appspot.com',
    iosBundleId: 'com.example.sGroup.RunnerTests',
  );
}
